[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept"
    Cross-Origin-Embedder-Policy = "credentialless"
